name: LogseqTaskViewer
options:
  bundleIdPrefix: com.kerim
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "0.0.1"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  LogseqTaskViewer:
    type: application
    platform: macOS
    sources:
      - path: LogseqTaskViewer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kerim.LogseqTaskViewer
        INFOPLIST_FILE: LogseqTaskViewer/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    scheme:
      testTargets:
        - LogseqTaskViewerTests

  LogseqTaskViewerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - LogseqTaskViewerTests
    dependencies:
      - target: LogseqTaskViewer
